#cloud-config
users:
  - name: ${vm_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: ${vm_password}
ssh_pwauth: true
package_update: true
packages:
  - curl
  - wget
  - git
  - htop
  - vim
  - net-tools
  - openssh-server
  - ufw
runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - ufw --force enable
  - ufw allow ssh
  - ufw allow 25565/tcp comment 'Minecraft Server'
  - ufw allow 25575/tcp comment 'Minecraft RCON'
  - sysctl -p
